import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillInstagram, AiFillYoutube, AiFillGithub } from 'react-icons/ai';
import MyPhoto from '../../public/my-photos.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const hoverTextStyle = "hover:text-violet-800";

  return (
    <>
      <Head>
        <title>Alfarizi's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Press+Start+2P&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
      </Head>

      <main className='px-10 font-inter'>

        {/* Navbar */}
        <nav className='relative'>
          <div className='fixed top-0 left-0 right-0 flex justify-between px-10 sm:px-20 md:px-30 lg:px-40 py-7 backdrop-blur-sm bg-white/30 duration-200'>
            <h1 className='font-pixel text-base'>ALFARIZI</h1>
            <ul className='flex items-center'>
              <li className='cursor-pointer text-gray-800 hover:text-violet-800 active:text-violet-500'><BsFillMoonStarsFill size={20} /></li>
              <li><a href="#" className='bg-gradient-to-r from-blue-600 to-teal-600 ml-5 p-2 text-gray-200 rounded-lg hover:from-blue-700 hover:to-teal-700 active:from-blue-900 active:to-teal-900'>Resume</a></li>
            </ul>
          </div>
        </nav>

        {/* Introduction about myself */}
        <section className='mt-36'>
          <div className='my-10 text-center'>
            <h2 className='text-3xl sm:text-5xl font-bold'>Moh Rizal Alfarizi</h2>
            <h3 className='text-lg font-semibold'>Physicist and Developer</h3>
            <p className='my-3 leading-normal text-sm mx-auto max-w-md'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti autem, corrupti, magni facilis voluptas fugit assumenda fugiat suscipit velit voluptatibus, illum totam!</p>
            <div className='pt-5 flex text-3xl justify-center content-center gap-10'>
              <a className='hover:text-violet-800 active:text-violet-500' href="#"><AiFillLinkedin /></a>
              <a className='hover:text-violet-800 active:text-violet-500' href="#"><AiFillInstagram /></a>
              <a className='hover:text-violet-800 active:text-violet-500' href="#"><AiFillGithub /></a>
              <a className='hover:text-violet-800 active:text-violet-500' href="#"><AiFillYoutube /></a>
            </div>
          </div>
          <div className='py-1 mx-auto max-w-[250px] max-h-[250px] bg-gradient-to-b from-cyan-600 to-teal-900 rounded-full overflow-hidden'>
            <Image src={MyPhoto} />
          </div>
        </section>

        {/* More information */}
        <section className='mt-20 mx-auto max-w-4xl sm:flex justify-center gap-10 items-center shadow-2xl border-4 border-y-indigo-800 border-x-transparent sm:border-x-indigo-800 sm:border-y-transparent p-5 rounded-2xl transition'>
          <h3 className='text-center font-semibold text-2xl sm:text-3xl py-3'>Services I Offer</h3>
          <div className='flex flex-col gap-2 justify-between items-center'>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure <span className='text-teal-800 font-semibold'>veritatis</span> omnis minima quo deserunt voluptas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore nulla facilis modi quos, placeat, nihil a repellendus expedita ipsum officia sequi nam dicta corporis provident ducimus dolorem nobis aut ullam?</p>
            <p>Officia quibusdam a nisi porro, eaque at ab eligendi autem maiores <span className='text-teal-800 font-semibold'>voluptates</span> quaerat similique id. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium, commodi dignissimos? Facilis corporis repellat ipsum dignissimos aspernatur. Recusandae, error rem libero iure tenetur quod debitis sint? Iure quisquam repellendus nemo!</p>
          </div>
        </section>


        <div className='h-screen'>
        </div>
      </main>
    </>
  )
}
