import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { BsFillMoonStarsFill } from 'react-icons/bs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Alfarizi's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Press+Start+2P&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
      </Head>
      <main className='px-10 font-inter'>
        <section className='min-h-screen'>
          <nav className='flex justify-between py-10 '>
            <h1 className='font-pixel text-base'>ALFARIZI</h1>
            <ul className='flex items-center'>
              <li className='cursor-pointer text-gray-800 hover:text-violet-800'><BsFillMoonStarsFill size={20} /></li>
              <li><a href="#" className='bg-gradient-to-r from-blue-500 to-teal-500 mx-5 p-2 text-gray-200 rounded-lg hover:from-blue-700 hover:to-teal-700'>Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  )
}
